# Generated by Django 3.2 on 2021-12-29 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='time_minutest',
        ),
    ]
