# Generated by Django 3.2 on 2021-12-29 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_recipe_time_minutest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
